### PR TITLE
Use interface{} as params per mihome-binary-protocol

### PR DESCRIPTION
**Pull request by yzlai**
Correct #2

### CODE REVIEW

**Comment by nickw444** [comment]
Awesome, thanks for the contribution. I didn’t get a chance to test this this weekend, however I’ll try my best to set aside a little time to get this merged in the next few days. Thanks!!

**Comment by qtopie** [comment]
Is this project still under maintenance? @nickw444

**Comment by nickw444** [comment]
Apologies. I’ve really let the ball drop on this one. Long story short; a few other projects have come up which ultimately have left this one with a lower priority. I still plan on eventually getting back to this and finishing it off (along with my MiiO Apple HomeKit bridge).

**Comment by nickw444** [comment]
Implemented in #4

**Pull request closed without merging**
